from app import db
from datetime import datetime

class PlayerStatsTable(db.Model):

	id = db.Column(db.Integer, primary_key=True)
	TimeStamp = db.Column(db.DateTime, nullable = False, default = datetime.today())
	KW = db.Column(db.String(4), nullable = False, default = datetime.today().strftime("%V"))
	playerName = db.Column(db.String(30))
	apiLastChecked = db.Column(db.String(50))
	lastUpdated = db.Column(db.String(40))
	ScorePerMinute = db.Column(db.Float)
	KdRatio = db.Column(db.Float)	
	Kills = db.Column(db.Integer)
	Deaths = db.Column(db.Integer)
	Damage = db.Column(db.Integer)
	Assists = db.Column(db.Integer)
	KillsAggregated = db.Column(db.Integer)
	AssistsAsKills = db.Column(db.Integer)
	ShotsTaken = db.Column(db.Integer)
	ShotsHit = db.Column(db.Integer)
	ShotsAccuracy = db.Column(db.Float)
	KillStreak = db.Column(db.Integer)
	DogtagsTaken = db.Column(db.Integer)
	AvengerKills = db.Column(db.Integer)
	SaviorKills = db.Column(db.Integer)
	Headshots = db.Column(db.Integer)
	SuppressionAssists = db.Column(db.Integer)
	LongestHeadshot = db.Column(db.Integer)
	KillsPerMinute = db.Column(db.Float)
	DamagePerMinute = db.Column(db.Float)
	Heals = db.Column(db.Integer)
	Revives = db.Column(db.Integer)
	RevivesRecieved = db.Column(db.Integer)
	Resupplies = db.Column(db.Integer)
	Repairs = db.Column(db.Integer)
	AceSquad = db.Column(db.Integer)
	SquadSpawns = db.Column(db.Integer)
	SquadWipes = db.Column(db.Integer)
	OrdersCompleted = db.Column(db.Integer)
	WlPercentage = db.Column(db.Float)
	Wins = db.Column(db.Integer)
	Losses = db.Column(db.Integer)
	Draws = db.Column(db.Integer)
	Rounds = db.Column(db.Integer)
	RoundsPlayed = db.Column(db.Integer)
	Rank = db.Column(db.Integer)
	RankScore = db.Column(db.Integer)
	TimePlayed = db.Column(db.Integer)
	ScoreRound = db.Column(db.Integer)
	ScoreGeneral = db.Column(db.Integer)
	ScoreCombat = db.Column(db.Integer)
	ScoreDefensive = db.Column(db.Integer)
	ScoreObjective = db.Column(db.Integer)
	ScoreBonus = db.Column(db.Integer)
	ScoreSquad = db.Column(db.Integer)
	ScoreAward = db.Column(db.Integer)
	ScoreAssault = db.Column(db.Integer)
	ScoreMedic = db.Column(db.Integer)
	ScoreSupport = db.Column(db.Integer)
	ScoreRecon = db.Column(db.Integer)
	ScoreAir = db.Column(db.Integer)
	ScoreLand = db.Column(db.Integer)
	ScoreTanks = db.Column(db.Integer)
	ScoreTransports = db.Column(db.Integer)

	def __repr__(self):
		return '<User %r>' % self.playerName

class FireStormTable(db.Model):

	id = db.Column(db.Integer, primary_key=True)
	TimeStamp = db.Column(db.DateTime, nullable = False, default = datetime.today())
	KW = db.Column(db.String(4), nullable = False, default = datetime.today().strftime("%V"))
	playerName = db.Column(db.String(30))
	apiLastChecked = db.Column(db.String(50))
	lastUpdated = db.Column(db.String(40))
	CapturePoints = db.Column(db.Integer)
	Deaths = db.Column(db.Integer)	
	Downs = db.Column(db.Integer)
	Headshots = db.Column(db.Integer)
	KdRatio = db.Column(db.Float)
	Healing = db.Column(db.Integer)
	Kills = db.Column(db.Integer)
	KillsMelee = db.Column(db.Integer)
	KillsPerMatch = db.Column(db.Float)
	KillsPerMinute = db.Column(db.Float)
	MatchesPlayed = db.Column(db.Integer)
	Revives = db.Column(db.Integer)
	RoadKills = db.Column(db.Integer)
	Safes = db.Column(db.Integer)
	SoloLosses = db.Column(db.Integer)
	SoloWinPercentage = db.Column(db.Float)
	SoloWins = db.Column(db.Integer)
	SquadLosses = db.Column(db.Integer)
	SquadWinPercentage = db.Column(db.Float)
	SquadWins = db.Column(db.Integer)
	SupplyDrops = db.Column(db.Integer)
	Tanks = db.Column(db.Integer)
	TeamKills = db.Column(db.Integer)
	TimePlayed = db.Column(db.Integer)
	VehicleBreakouts = db.Column(db.Integer)
	VehicleWeaponKills = db.Column(db.Integer)
	VehiclesDestroyed = db.Column(db.Integer)
	
	def __repr__(self):
		return '<User %r>' % self.playerName

